---
title: "Assesing Demand for Transit Accessesible Apartments"
output: html_document
---
TO DO:
- Cache All tables
- Add shape file for Chicago boundaries 
- Add CTA data
- recreate buffers set to quarter mile
- Replicate graphs on changes 2009 - 2019
- create ring buffers for 



```{r}
library(tidyverse)
library(tidycensus)
library(sf)
library(kableExtra)
library(acs)

options(scipen=999)
options(tigris_class = "sf")

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

palette5 <- c("#f0f9e8","#bae4bc","#7bccc4","#43a2ca","#0868ac")

```



# CMAP Region 
```{r}
#  Income = B07011_001
# Pulling ACS Five year data (2005-2009) for the seven CMAP counties
cook09 <- 
  get_acs(geography = "tract", variables = c("B25026_001E","B02001_002E","B15001_050E",
                                             "B15001_009E","B19013_001E","B25058_001E",
                                             "B06012_002E"), 
          year=2009, state=17, county=031, geometry=T, output="wide", cache_table = TRUE) %>%
  st_transform('ESRI:102728') %>%
  rename(TotalPop = B25026_001E, Whites = B02001_002E,
         FemaleBachelors = B15001_050E, MaleBachelors = B15001_009E,
         MedHHInc = B19013_001E, MedRent = B25058_001E, 
         TotalPoverty = B06012_002E) %>%
  dplyr::select(-NAME, -starts_with("B")) %>%
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop,0),
         pctBachelors = ifelse(TotalPop > 0, ((FemaleBachelors + MaleBachelors) / TotalPop),0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop, 0),
         year = "2009", county = "Cook") %>%
  dplyr::select(-Whites, -FemaleBachelors, -MaleBachelors, -TotalPoverty) 



dupage09 <- 
  get_acs(geography = "tract", variables = c("B25026_001E","B02001_002E","B15001_050E",
                                             "B15001_009E","B19013_001E","B25058_001E",
                                             "B06012_002E", "B25026_001E"), 
          year=2009, state=17, county=043, geometry=T, output="wide", cache_table = TRUE) %>%
  st_transform('ESRI:102728') %>%
  rename(TotalPop = B25026_001E, Whites = B02001_002E,
         FemaleBachelors = B15001_050E, MaleBachelors = B15001_009E,
         MedHHInc = B19013_001E, MedRent = B25058_001E, 
         TotalPoverty = B06012_002E) %>%
  dplyr::select(-NAME, -starts_with("B")) %>%
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop,0),
         pctBachelors = ifelse(TotalPop > 0, ((FemaleBachelors + MaleBachelors) / TotalPop),0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop, 0),
         year = "2009", county = "Dupage") %>%
  dplyr::select(-Whites, -FemaleBachelors, -MaleBachelors, -TotalPoverty)

kane09 <- 
  get_acs(geography = "tract", variables = c("B25026_001E","B02001_002E","B15001_050E",
                                             "B15001_009E","B19013_001E","B25058_001E",
                                             "B06012_002E"), 
          year=2009, state=17, county=089, geometry=T, output="wide", cache_table = TRUE) %>%
  st_transform('ESRI:102728') %>%
  rename(TotalPop = B25026_001E, Whites = B02001_002E,
         FemaleBachelors = B15001_050E, MaleBachelors = B15001_009E,
         MedHHInc = B19013_001E, MedRent = B25058_001E, 
         TotalPoverty = B06012_002E) %>%
  dplyr::select(-NAME, -starts_with("B")) %>%
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop,0),
         pctBachelors = ifelse(TotalPop > 0, ((FemaleBachelors + MaleBachelors) / TotalPop),0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop, 0),
         year = "2009", county = "Kane") %>%
  dplyr::select(-Whites, -FemaleBachelors, -MaleBachelors, -TotalPoverty)

kendall09 <- 
  get_acs(geography = "tract", variables = c("B25026_001E","B02001_002E","B15001_050E",
                                             "B15001_009E","B19013_001E","B25058_001E",
                                             "B06012_002E"), 
          year=2009, state=17, county=093, geometry=T, output="wide",cache_table = TRUE) %>%
  st_transform('ESRI:102728') %>%
  rename(TotalPop = B25026_001E, Whites = B02001_002E,
         FemaleBachelors = B15001_050E, MaleBachelors = B15001_009E,
         MedHHInc = B19013_001E, MedRent = B25058_001E, 
         TotalPoverty = B06012_002E) %>%
  dplyr::select(-NAME, -starts_with("B")) %>%
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop,0),
         pctBachelors = ifelse(TotalPop > 0, ((FemaleBachelors + MaleBachelors) / TotalPop),0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop, 0),
         year = "2009", county = "Kendall") %>%
  dplyr::select(-Whites, -FemaleBachelors, -MaleBachelors, -TotalPoverty)

lake09  <- 
  get_acs(geography = "tract", variables = c("B25026_001E","B02001_002E","B15001_050E",
                                             "B15001_009E","B19013_001E","B25058_001E",
                                             "B06012_002E"), 
          year=2009, state=17, county=097, geometry=T, output="wide", cache_table = TRUE) %>%
  st_transform('ESRI:102728') %>%
  rename(TotalPop = B25026_001E, Whites = B02001_002E,
         FemaleBachelors = B15001_050E, MaleBachelors = B15001_009E,
         MedHHInc = B19013_001E, MedRent = B25058_001E, 
         TotalPoverty = B06012_002E) %>%
  dplyr::select(-NAME, -starts_with("B")) %>%
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop,0),
         pctBachelors = ifelse(TotalPop > 0, ((FemaleBachelors + MaleBachelors) / TotalPop),0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop, 0),
         year = "2009", county = "Lake") %>%
  dplyr::select(-Whites, -FemaleBachelors, -MaleBachelors, -TotalPoverty)

mchenry09 <- 
  get_acs(geography = "tract", variables = c("B25026_001E","B02001_002E","B15001_050E",
                                             "B15001_009E","B19013_001E","B25058_001E",
                                             "B06012_002E"), 
          year=2009, state=17, county=111, geometry=T, output="wide", cache_table = TRUE) %>%
  st_transform('ESRI:102728') %>%
  rename(TotalPop = B25026_001E, Whites = B02001_002E,
         FemaleBachelors = B15001_050E, MaleBachelors = B15001_009E,
         MedHHInc = B19013_001E, MedRent = B25058_001E, 
         TotalPoverty = B06012_002E) %>%
  dplyr::select(-NAME, -starts_with("B")) %>%
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop,0),
         pctBachelors = ifelse(TotalPop > 0, ((FemaleBachelors + MaleBachelors) / TotalPop),0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop, 0),
         year = "2009", county = "McHenry") %>%
  dplyr::select(-Whites, -FemaleBachelors, -MaleBachelors, -TotalPoverty)

will09 <- 
  get_acs(geography = "tract", variables = c("B25026_001E","B02001_002E","B15001_050E",
                                             "B15001_009E","B19013_001E","B25058_001E",
                                             "B06012_002E"), 
          year=2009, state=17, county=197, geometry=T, output="wide", cache_table = TRUE) %>%
  st_transform('ESRI:102728') %>%
  rename(TotalPop = B25026_001E, Whites = B02001_002E,
         FemaleBachelors = B15001_050E, MaleBachelors = B15001_009E,
         MedHHInc = B19013_001E, MedRent = B25058_001E, 
         TotalPoverty = B06012_002E) %>%
  dplyr::select(-NAME, -starts_with("B")) %>%
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop,0),
         pctBachelors = ifelse(TotalPop > 0, ((FemaleBachelors + MaleBachelors) / TotalPop),0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop, 0),
         year = "2009", county = "Will") %>%
  dplyr::select(-Whites, -FemaleBachelors, -MaleBachelors, -TotalPoverty)

# Creating one tract data frame for the CMAP region
tracts09 <- rbind(cook09,dupage09,kane09,kendall09,lake09,mchenry09,will09)





# Pulling ACS Five year data (2015-2019) for the seven CMAP counties
cook19 <- 
  get_acs(geography = "tract", variables = c("B25026_001E","B02001_002E","B15001_050E",
                                             "B15001_009E","B19013_001E","B25058_001E",
                                             "B06012_002E"), 
          year=2019, state=17, county=031, geometry=T, output="wide", cache_table = TRUE) %>%
  st_transform('ESRI:102728') %>%
  rename(TotalPop = B25026_001E, Whites = B02001_002E,
         FemaleBachelors = B15001_050E, MaleBachelors = B15001_009E,
         MedHHInc = B19013_001E, MedRent = B25058_001E, 
         TotalPoverty = B06012_002E) %>%
  dplyr::select(-NAME, -starts_with("B")) %>%
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop,0),
         pctBachelors = ifelse(TotalPop > 0, ((FemaleBachelors + MaleBachelors) / TotalPop),0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop, 0),
         year = "2019", county = "Cook") %>%
  dplyr::select(-Whites, -FemaleBachelors, -MaleBachelors, -TotalPoverty) 

dupage19 <- 
  get_acs(geography = "tract", variables = c("B25026_001E","B02001_002E","B15001_050E",
                                             "B15001_009E","B19013_001E","B25058_001E",
                                             "B06012_002E"), 
          year=2019, state=17, county=043, geometry=T, output="wide", cache_table = TRUE) %>%
  st_transform('ESRI:102728') %>%
  rename(TotalPop = B25026_001E, Whites = B02001_002E,
         FemaleBachelors = B15001_050E, MaleBachelors = B15001_009E,
         MedHHInc = B19013_001E, MedRent = B25058_001E, 
         TotalPoverty = B06012_002E) %>%
  dplyr::select(-NAME, -starts_with("B")) %>%
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop,0),
         pctBachelors = ifelse(TotalPop > 0, ((FemaleBachelors + MaleBachelors) / TotalPop),0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop, 0),
         year = "2019", county = "Dupage") %>%
  dplyr::select(-Whites, -FemaleBachelors, -MaleBachelors, -TotalPoverty)

kane19 <- 
  get_acs(geography = "tract", variables = c("B25026_001E","B02001_002E","B15001_050E",
                                             "B15001_009E","B19013_001E","B25058_001E",
                                             "B06012_002E"), 
          year=2019, state=17, county=089, geometry=T, output="wide", cache_table = TRUE) %>%
  st_transform('ESRI:102728') %>%
  rename(TotalPop = B25026_001E, Whites = B02001_002E,
         FemaleBachelors = B15001_050E, MaleBachelors = B15001_009E,
         MedHHInc = B19013_001E, MedRent = B25058_001E,
         TotalPoverty = B06012_002E) %>%
  dplyr::select(-NAME, -starts_with("B")) %>%
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop,0),
         pctBachelors = ifelse(TotalPop > 0, ((FemaleBachelors + MaleBachelors) / TotalPop),0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop, 0),
         year = "2019", county = "Kane") %>%
  dplyr::select(-Whites, -FemaleBachelors, -MaleBachelors, -TotalPoverty)

kendall19 <- 
  get_acs(geography = "tract", variables = c("B25026_001E","B02001_002E","B15001_050E",
                                             "B15001_009E","B19013_001E","B25058_001E",
                                             "B06012_002E"), 
          year=2019, state=17, county=093, geometry=T, output="wide", cache_table = TRUE) %>%
  st_transform('ESRI:102728') %>%
  rename(TotalPop = B25026_001E, Whites = B02001_002E,
         FemaleBachelors = B15001_050E, MaleBachelors = B15001_009E,
         MedHHInc = B19013_001E, MedRent = B25058_001E, 
         TotalPoverty = B06012_002E) %>%
  dplyr::select(-NAME, -starts_with("B")) %>%
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop,0),
         pctBachelors = ifelse(TotalPop > 0, ((FemaleBachelors + MaleBachelors) / TotalPop),0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop, 0),
         year = "2019", county = "Kendall") %>%
  dplyr::select(-Whites, -FemaleBachelors, -MaleBachelors, -TotalPoverty)

lake19  <- 
  get_acs(geography = "tract", variables = c("B25026_001E","B02001_002E","B15001_050E",
                                             "B15001_009E","B19013_001E","B25058_001E",
                                             "B06012_002E"), 
          year=2019, state=17, county=097, geometry=T, output="wide", cache_table = TRUE) %>%
  st_transform('ESRI:102728') %>%
  rename(TotalPop = B25026_001E, Whites = B02001_002E,
         FemaleBachelors = B15001_050E, MaleBachelors = B15001_009E,
         MedHHInc = B19013_001E, MedRent = B25058_001E,
         TotalPoverty = B06012_002E) %>%
  dplyr::select(-NAME, -starts_with("B")) %>%
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop,0),
         pctBachelors = ifelse(TotalPop > 0, ((FemaleBachelors + MaleBachelors) / TotalPop),0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop, 0),
         year = "2019", county = "Lake") %>%
  dplyr::select(-Whites, -FemaleBachelors, -MaleBachelors, -TotalPoverty)

mchenry19 <- 
  get_acs(geography = "tract", variables = c("B25026_001E","B02001_002E","B15001_050E",
                                             "B15001_009E","B19013_001E","B25058_001E",
                                             "B06012_002E"), 
          year=2019, state=17, county=111, geometry=T, output="wide", cache_table = TRUE) %>%
  st_transform('ESRI:102728') %>%
  rename(TotalPop = B25026_001E, Whites = B02001_002E,
         FemaleBachelors = B15001_050E, MaleBachelors = B15001_009E,
         MedHHInc = B19013_001E, MedRent = B25058_001E, 
         TotalPoverty = B06012_002E) %>%
  dplyr::select(-NAME, -starts_with("B")) %>%
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop,0),
         pctBachelors = ifelse(TotalPop > 0, ((FemaleBachelors + MaleBachelors) / TotalPop),0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop, 0),
         year = "2019", county = "McHenry") %>%
  dplyr::select(-Whites, -FemaleBachelors, -MaleBachelors, -TotalPoverty)

will19 <- 
  get_acs(geography = "tract", variables = c("B25026_001E","B02001_002E","B15001_050E",
                                             "B15001_009E","B19013_001E","B25058_001E",
                                             "B06012_002E", "B25026_001E"), 
          year=2019, state=17, county=197, geometry=T, output="wide", cache_table = TRUE) %>%
  st_transform('ESRI:102728') %>%
  rename(TotalPop = B25026_001E, Whites = B02001_002E,
         FemaleBachelors = B15001_050E, MaleBachelors = B15001_009E,
         MedHHInc = B19013_001E, MedRent = B25058_001E, 
         TotalPoverty = B06012_002E) %>%
  dplyr::select(-NAME, -starts_with("B")) %>%
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop,0),
         pctBachelors = ifelse(TotalPop > 0, ((FemaleBachelors + MaleBachelors) / TotalPop),0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop, 0), 
         year = "2019", county = "Will") %>%
  dplyr::select(-Whites, -FemaleBachelors, -MaleBachelors, -TotalPoverty, )



tracts19 <- rbind(cook19,dupage19,kane19,kendall19,lake19,mchenry19,will19)

allTracts_cmap <- rbind(tracts09,tracts19)

ggplot() + 
  geom_sf(data = tracts19) + 
  mapTheme()
```


Wrangling Metra data from https://data.cityofchicago.org/Transportation/Metra-Stations/nqm8-q2ym


```{r}

metra_stops <- st_read("/Users/noahanderson/Documents/GitHub/chicago-TOD/DATA/MetraStation/MetraStations.shp") %>% 
  st_transform('ESRI:102728') 

# Filters out stops outside of the CMAP region
metra_cmap <- st_intersection(tracts19,metra_stops)

# Creates a mile buffer around the metra stops 
metra_buffer <- st_union(st_buffer(metra_cmap,5280/2)) %>%
  st_sf()



tract_buffer <- st_centroid(tracts09)[metra_buffer,] %>%
  st_drop_geometry() %>%
  left_join(dplyr::select(tracts09,GEOID)) %>%
  st_sf()



ggplot() +
  
  geom_sf(data = st_union(tracts09)) + 
  
  geom_sf(data = tract_buffer) +
  
  labs(title = "CMAP Region \n Metra Buffer") +
  
  mapTheme()

```


```{r}
# Combining CMAP 2009 and 2019 ACS data 
allTracts_cmap.group <- 
  rbind( 
    st_centroid(allTracts_cmap)[tract_buffer,] %>%
      st_drop_geometry() %>%
      left_join(allTracts_cmap) %>%
      st_sf() %>%
      mutate(TOD = "TOD"),
    st_centroid(allTracts_cmap)[tract_buffer, op = st_disjoint] %>%
      st_drop_geometry() %>%
      left_join(allTracts_cmap) %>%
      st_sf() %>%
      mutate(TOD = "Non-TOD")) %>%
  mutate(MedRent.inf = ifelse(year == "2009", MedRent * 1.2, MedRent)) 
# 2009 rent is adjusted for inflation 

```
Creating the Same graphs as in chapter 1
```{r}
allTracts_cmap.Summary <- 
  st_drop_geometry(allTracts_cmap.group) %>%
    group_by(year, TOD) %>%
    summarize(Rent = mean(MedRent.inf, na.rm = T),
              Population = mean(TotalPop, na.rm = T),
              Percent_White = mean(pctWhite, na.rm = T),
              Percent_Bach = mean(pctBachelors, na.rm = T),
              Percent_Poverty = mean(pctPoverty, na.rm = T))

kable(allTracts_cmap.Summary) %>%
  kable_styling() %>%
  footnote(general_title = "\n",
           general = "Table 1.2")


allTracts_cmap.Summary %>%
  gather(Variables, Value, -year, -TOD) %>%
  ggplot(aes(year, Value, fill = TOD)) +
    geom_bar(stat = "identity", position = "dodge") +
    facet_wrap(~Variables, scales = "free", ncol=5) +
    scale_fill_manual(values = c("#bae4bc", "#0868ac")) +
    labs(title = "Indicator differences across time and space")  + theme(legend.position="bottom")


```


Rent as a function of distance to stations CMAP
```{r}
allTracts_cmap.rings <-
  st_join(st_centroid(dplyr::select(tracts19, GEOID, year)), 
          multipleRingBuffer(st_union(metra_stops), 47520, 5280/2)) %>%
  st_drop_geometry() %>%
  left_join(dplyr::select(allTracts, GEOID, MedRent, year), 
            by=c("GEOID"="GEOID", "year"="year")) %>%
  st_sf() %>%
  mutate(distance = distance / 5280) #convert to miles

medRent_Distance_cmap <-  allTracts_cmap.rings %>%
  group_by(distance) %>%
  summarize(mean_rent = mean(MedRent, na.rm = TRUE))

ggplot() + 
  
  geom_line(data = medRent_Distance_cmap, aes(x = distance, y = mean_rent)) 



```

# Chicago Only

```{r}
chicago_neighborhoods <- st_read("https://raw.githubusercontent.com/noahba65/chicago-TOD/main/DATA/chicago_boundary.geojson") %>%
  st_transform('ESRI:102728') %>% st_sf()

chicago_boundary <- st_union(chicago_neighborhoods) %>% 
  st_sf()

cta_stops <- st_read("https://raw.githubusercontent.com/ChicagoCityscape/gis-data/master/stations_cta/cta_entrances.geojson") %>%
  st_transform('ESRI:102728') %>% st_sf()

# Creating Chicago only ACS tract data for 2009 and 2019
chicago09 <- st_intersection(chicago_boundary, cook09)
chicago19 <- st_intersection(chicago_boundary,cook19) 

allTracts_chicago <- rbind(chicago09,chicago19)


# Creating CTA buffer
cta_buffer <- st_union(st_buffer(cta_stops,5280/4)) %>%
  st_sf()



# Cannot get this to work
tract_buffer_chicago <- st_centroid(chicago09)[cta_buffer,] %>%
  st_drop_geometry() %>%
  left_join(dplyr::select(chicago09,GEOID)) %>%
  st_sf()



ggplot() +
  geom_sf(data = chicago_tracts, aes(fill = MedRent)) + 
  labs(fill = "Median Rent (USD)") + ggtitle("Rent Distribution in Chicago") + 
  mapTheme() 
ggplot() +
  geom_sf(data = st_union(chicago09)) +
  geom_sf(data = tract_buffer_chicago, fill = "red")  + mapTheme()

```


```{r}

class(allTracts_chicago)
class(allTracts_cmap)
# Combining CMAP 2009 and 2019 ACS data 
allTracts_chicago.group <- 
  rbind( 
    st_centroid(allTracts_chicago)[tract_buffer_chicago,] %>%
      st_drop_geometry() %>%
      left_join(allTracts_chicago) %>%
      st_sf() %>%
      mutate(TOD = "TOD"),
    st_centroid(allTracts_chicago)[tract_buffer_chicago, op = st_disjoint] %>%
      st_drop_geometry() %>%
      left_join(allTracts_chicago) %>%
      st_sf() %>%
      mutate(TOD = "Non-TOD")) %>%
  mutate(MedRent.inf = ifelse(year == "2009", MedRent * 1.2, MedRent)) 
# 2009 rent is adjusted for inflation 

allTracts_chicago.Summary <- 
  st_drop_geometry(allTracts_chicago.group) %>%
    group_by(year, TOD) %>%
    summarize(Rent = mean(MedRent.inf, na.rm = T),
              Population = mean(TotalPop, na.rm = T),
              Percent_White = mean(pctWhite, na.rm = T),
              Percent_Bach = mean(pctBachelors, na.rm = T),
              Percent_Poverty = mean(pctPoverty, na.rm = T))

kable(allTracts_chicago.Summary) %>%
  kable_styling() %>%
  footnote(general_title = "\n",
           general = "Table 1.2")


allTracts_chicago.Summary %>%
  gather(Variables, Value, -year, -TOD) %>%
  ggplot(aes(year, Value, fill = TOD)) +
    geom_bar(stat = "identity", position = "dodge") +
    facet_wrap(~Variables, scales = "free", ncol=5) +
    scale_fill_manual(values = c("#bae4bc", "#0868ac")) +
    labs(title = "Indicator differences across time and space")  + theme(legend.position="bottom")



```
Rent as a function of distance to stations CMAP
```{r}
allTracts_chicago.rings <-
  st_join(st_centroid(dplyr::select(chicago19, GEOID, year)), 
          multipleRingBuffer(st_union(cta_stops), 47520, 5280/2)) %>%
  st_drop_geometry() %>%
  left_join(dplyr::select(allTracts, GEOID, MedRent, year), 
            by=c("GEOID"="GEOID", "year"="year")) %>%
  st_sf() %>%
  mutate(distance = distance / 5280) #convert to miles

medRent_Distance_chicago <-  allTracts_chicago.rings %>%
  group_by(distance) %>%
  summarize(mean_rent = mean(MedRent, na.rm = TRUE))

ggplot() + 
  
  geom_line(data = medRent_Distance_chicago, aes(x = distance, y = mean_rent)) 



```
