```{r}
library(tidyverse)
library(sf)
library(kableExtra)
library(urbnmapr)
options(scipen=999)
options(tigris_class = "sf")

# Investigate the details of this later
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r") 
```

/Users/noahanderson/Downloads/IL_BNDY_County/IL_BNDY_County_Ln.shp
```{r}
metra_stop <-  st_read("https://raw.githubusercontent.com/noahba65/chicago-TOD/main/DATA/Metra_Stations_(2019).geojson") 
metra_stop <- metra_stop %>%
  st_transform('ESRI:102728')  %>%
  st_sf()
county_boundaries <- st_read("/Users/noahanderson/Downloads/IL_BNDY_County/IL_BNDY_County_Ln.shp") %>%
  st_transform('ESRI:102728')  %>%
  st_sf()

metra_no_NA <- metra_stop %>%
  filter(Pk_Rate_17 != 0, Pk_Rate_17 != "NA", AllOff_18 != "NA" ) 
metra_no_NA$Pk_Rate_17<- as.numeric(as.character(metra_no_NA$Pk_Rate_17))



ggplot() +
  geom_point(data = metra_no_NA, aes(Pk_Rate_17,AllOff_18)) + 
   geom_smooth(data = metra_no_NA, aes(Pk_Rate_17,AllOff_18))



```




Trying Urbanmapr

```{r}
states <- urbnmapr::states
View(counties)
il_counties <- urbnmapr::counties %>%
  filter(state_name == "Illinois")

ggplot() +
  geom_polygon(data = il_counties, aes(x = long, y = lat, group = group))  +
  mapTheme()
```